services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cda-final-project-db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5824:5432'