services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cda-final-project-db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
    ports:
      - '5824:5432'

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # the port the web interface should be accessible on
      - '5000:80'
      # the port the SMTP server should be accessible on
      - '25:25'
      # the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
        
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  smtp4dev-data:
  mongo_data: