spring:
  datasource:
    url: jdbc:postgresql://localhost:5824/cda-final-project-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      mode: always