name: Build & Release Spring Boot

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Permet de déclencher manuellement

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Version de Java (OpenJDK Temurin)
          java-version: '17'
          cache: 'maven'

      - name: Build avec Maven
        run: mvn clean package -DskipTests

#      - name: Exécuter les tests
#        run: mvn test

      - name: Sauvegarde de l’artefact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
          retention-days: 7