name: Build & Push Docker Image

on:
  workflow_run:
    workflows: ["Build Spring Boot"]
    types:
      - completed

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Télécharger l’artefact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/

      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build de l’image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest .

      - name: Push de l’image Docker sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mon-projet:latest