name: Build, Test, Analyze & Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main


jobs:
  build:
    name: Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
  sonar:
    name: Sonar Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cda-exam_cda-final-project-backend
  docker:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - build
      - sonar
    steps:
      - name: Télécharger l’artefact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: target/
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Connexion à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build de l’image Docker
        run: |
          docker build --no-cache --rm -t ${{ secrets.DOCKER_USERNAME }}/cda-final-project-backend:latest .
      - name: Push de l’image Docker sur Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cda-final-project-backend:latest